# frozen_string_literal: true

EXAMPLE = <<~TEXT.lines
  ....#.....
  .........#
  ..........
  ..#.......
  .......#..
  ..........
  .#..^.....
  ........#.
  #.........
  ......#...
TEXT

start = EXAMPLE.each_with_index.map { _1.include?('^') }
start_y = start.index { _1 }
start_x = EXAMPLE[start_y].index('^')

guard = Complex(start_x, start_y)

p guard
